package com.husj.screen;

import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.screen.ScreenHandlerType;
import net.minecraft.util.Identifier;

public class ModScreenHandlers {
    public static final ScreenHandlerType<DisassemblerScreenHandler> DISASSEMBLER_SCREEN_HANDLER = 
        Registry.register(Registries.SCREEN_HANDLER, 
            Identifier.of("husj", "disassembler"),
            new ScreenHandlerType<>(new ScreenHandlerType.Factory<DisassemblerScreenHandler>() {
                @Override
                public DisassemblerScreenHandler create(int syncId, net.minecraft.entity.player.PlayerInventory playerInventory) {
                    return new DisassemblerScreenHandler(syncId, playerInventory);
                }
            }, null));

    public static void registerScreenHandlers() {
        // 注册在Husj类中调用
    }
}
