package com.husj;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroups {
    public static final ItemGroup HUSJ_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Husj.MOD_ID, "husj_group"),
            FabricItemGroup.builder()
                    .displayName(Text.translatable("itemgroup.husj"))
                    .icon(() -> new ItemStack(ModBlocks.DISASSEMBLER_BLOCK))
                    .entries((displayContext, entries) -> {
                        entries.add(ModBlocks.DISASSEMBLER_BLOCK);
                    }).build());

    public static void registerItemGroups() {
        Husj.LOGGER.info("Registering Item Groups for " + Husj.MOD_ID);
    }
}
